print("========================================================")
print("                 Input Jumlah Keluarga")
print("========================================================")
jum_kel = int(input("Masukkan jumlah keluarga : "))
print("========================================================")
print("========================================================")
print("              Input Nama Anggota Keluarga")
print("========================================================")
bapak = input("Masukkan nama bapak : ")
ibu = input("Masukkan nama ibu : ")
k1 = input("Masukkan nama kakak pertama : ")
k2 = input("Masukkan nama kakak kedua : ")
k3 = input("Masukkan nama kakak ketiga : ")
k4 = input("Masukkan nama kakak keempat : ")
saya = input("Masukkan nama saya : ")
adek = input("Masukkan nama adek : ")
print("========================================================")
print("========================================================")
print("               Input Umur Anggota Keluarga")
print("========================================================")
umurBapak = int(input("Masukkan umur bapak : "))
umurIbu = int(input("Masukkan umur ibu : "))
umurk1 = int(input("Masukkan umur kakak pertama :"))
umurk2 = int(input("Masukkan umur kakak kedua :"))
umurk3 = int(input("Masukkan umur kakak ketiga :"))
umurk4 = int(input("Masukkan umur kakak keempat :"))
umurSaya = int(input("Masukkan umur saya : "))
umurAdek = int(input("Masukkan umur adek : "))
print("========================================================")
print("========================================================")
print("                     Data Keluarga")
print("========================================================")
print("Jumlah anggota keluarga saya :",jum_kel)
print("Nama bapak saya",bapak,"berumur",umurBapak,"tahun")
print("Nama ibu saya",ibu,"berumur",umurIbu,"tahun")
print("Nama kakak pertama saya",k1,"berumur",umurk1,"tahun")
print("Nama kakak kedua saya",k2,"berumur",umurk2,"tahun")
print("Nama kakak ketiga saya",k3,"berumur",umurk3,"tahun")
print("Nama kakak keempat saya",k4,"berumur",umurk4,"tahun")
print("Nama saya",saya,"berumur",umurSaya,"tahun")
print("Nama adek saya",adek,"berumur",umurAdek,"tahun")
print("========================================================")